brain_node:
  ros__parameters:
    game:
      team_id: 27 # consistant with GameControl
      player_id: 0 # 0 | 1 | 2 | 3
      field_type: "adult_size" # adult_size | kid_size 
      player_role: "striker" # striker | goal_keeper
      player_start_pos: "right" # right | left
      
    robot:
      robot_height: 1.0
      odom_factor: 1.2
      vx_factor: 0.90
      yaw_offset: 0.10
    
    enable_com: true

    rerunLog:
      enable: false
      server_addr: "192.168.30.188:9876"
      img_interval: 1
